export const operationsPage = `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Office operations</title>
<style>body{margin:0;background:#101825;color:#edf3fa;font:16px system-ui;line-height:1.5}main{max-width:1100px;margin:auto;padding:32px 24px}a{color:#86d9ff}header{display:flex;justify-content:space-between;align-items:center;gap:20px}h1{margin:0}p{color:#b8c7d8}section{background:#1b293b;border:1px solid #344860;border-radius:12px;padding:20px;margin:20px 0}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:10px;border-bottom:1px solid #344860;overflow-wrap:anywhere}th{color:#a7bed7}.metrics{display:flex;gap:20px;flex-wrap:wrap}.metrics b{display:block;font-size:28px;color:#86d9ff}.warn{color:#ffbf82}button{background:#86d9ff;color:#101825;border:0;border-radius:6px;padding:10px 16px;font:inherit;cursor:pointer}#freshness{padding:12px 0}h2{margin-top:0}@media(max-width:600px){main{padding:18px 12px}header{align-items:start;flex-direction:column}th,td{padding:6px;font-size:14px}}</style>
<main><header><div><h1>Office operations</h1><a href="/lite">Open office</a></div><button id="refresh">Refresh now</button></header><p>Live queue and worker observations. A finished task means its process ended; review its outcome and pull request before treating work as shipped. Revenue and provider billing are not measured here.</p><div id="freshness" role="status">Connecting…</div><div id="floors"></div></main>
<script>
const root=document.getElementById('floors'),status=document.getElementById('freshness'),button=document.getElementById('refresh');let last=0,busy=false;
function node(tag,text,parent){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(parent)parent.append(n);return n}
function table(parent,headers,rows){const t=node('table',undefined,parent),head=node('tr',undefined,node('thead',undefined,t));headers.forEach(h=>node('th',h,head));const body=node('tbody',undefined,t);rows.forEach(row=>{const tr=node('tr',undefined,body);row.forEach(v=>node('td',v||'—',tr))})}
async function refresh(){if(busy)return;busy=true;button.disabled=true;try{const response=await fetch('/api/operations',{cache:'no-store',signal:AbortSignal.timeout(10000)});if(!response.ok)throw Error(response.status===401?'Session expired. Open the office and sign in again.':'Server returned '+response.status);const data=await response.json();const fragment=document.createDocumentFragment();data.floors.forEach(f=>{const section=node('section',undefined,fragment);node('h2',f.name,section);if(f.paused)node('p','Queue paused (worker limit 0).',section).className='warn';const metrics=node('div',undefined,section);metrics.className='metrics';Object.entries(f.counts).forEach(([key,value])=>{const item=node('div',undefined,metrics);node('b',String(value),item);node('span',key,item)});f.warnings.forEach(w=>node('p',w,section).className='warn');node('h3','Workers',section);if(f.workers.length)table(section,['Name','Status'],f.workers.map(w=>[w.name,w.status]));else node('p','No seated workers.',section);node('h3','Tasks',section);if(f.tasks.length)table(section,['Task','Status / outcome','Worker','Error'],f.tasks.map(t=>[t.title,t.status+(t.outcome?' / '+t.outcome:''),t.workerName,t.error]));else node('p','No queued tasks.',section)});if(!data.floors.length)node('p','No open floors.',fragment);root.replaceChildren(fragment);last=data.observedAt;status.className='';status.textContent='Observed '+new Date(last).toLocaleString()+' · refreshes every 10 seconds';}catch(error){status.className='warn';status.textContent='Refresh failed: '+error.message+(last?' Last successful observation: '+new Date(last).toLocaleString()+'. Displayed data may be stale.':' No observation available.');}finally{busy=false;button.disabled=false}}
button.addEventListener('click',refresh);refresh();setInterval(refresh,10000);
</script></html>`;
